language: node_js

cache:
  yarn: true

stages:
  - lint
  - docker-hub
  - deploy-on-heroku

jobs:
  include:

    - stage: lint
      script:
        - yarn run lint

    - stage: docker-hub
      sudo: required
      services:
        - docker
      script:
        - yarn run build
        - docker build -t felippemauricio/challenge-charlie .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push felippemauricio/challenge-charlie
        - docker tag felippemauricio/challenge-charlie felippemauricio/challenge-charlie:$TRAVIS_COMMIT
        - docker push felippemauricio/challenge-charlie:$TRAVIS_COMMIT
      on:
        branch: master

    - stage: deploy-on-heroku
      sudo: required
      provider: heroku
      services:
        - docker
      script:
        - yarn run build
        - heroku container:login
        - heroku container:push web -a challenge-charlie
        - heroku container:release web -a challenge-charlie
      on:
        branch: master
