version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - proxy
  proxy:
    build: ./server
    command: python api/app.py
    ports:
      - "5000:5000"