version: '3.9'

services:
    nginx:
        container_name: nginx-production
        build:
            context: .
            dockerfile: prod.dockerfile
            target: production-stage
        ports:
             - 3000:80
        restart: always