version: '3.7'
services:
    app:
        container_name: challenge-charlie
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'           
        ports:
            - '3000:80'
        environment:
            - NODE_ENV=development