version: '3.9'

services:
    application-test:
        container_name: application-test
        build:
            context: .
            dockerfile: test.dockerfile
            target: base-stage
        entrypoint: yarn test
        volumes:
          - ./test:/app/test
