version: '3'

services:
    charlie_challenge_dev:
        build:
            context: .
            args:
                - NODE_ENV=development
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 8080:8080
            - 9229:9229
        command: npm run dev
