version: "3.8"
services:
    dev:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        volumes:
            - "/app/node_modules"
            - "./:/app"
