version: '3'

services:
    rr-proxy_prod:
        build:
            context: .
            args:
                - NODE_ENV=production
        ports:
            - 8080:8080
        command: npm run start
        restart: always
